artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/14/15b5e7f4eb4446949e0a4562a186286b/artifacts
end_time: 1638143495505
entry_point_name: ''
experiment_id: '14'
lifecycle_stage: active
name: ''
run_id: 15b5e7f4eb4446949e0a4562a186286b
run_uuid: 15b5e7f4eb4446949e0a4562a186286b
source_name: ''
source_type: 4
source_version: ''
start_time: 1638143454506
status: 4
tags: []
user_id: kaushik
