artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/6/6e16c2c2dd5b4b75b5f0bd932ead1fe2/artifacts
end_time: 1636404452474
entry_point_name: ''
experiment_id: '6'
lifecycle_stage: active
name: ''
run_id: 6e16c2c2dd5b4b75b5f0bd932ead1fe2
run_uuid: 6e16c2c2dd5b4b75b5f0bd932ead1fe2
source_name: ''
source_type: 4
source_version: ''
start_time: 1636404452464
status: 3
tags: []
user_id: root
