artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/13/c78c8e28be2a4394885c4a2b5aa79e56/artifacts
end_time: 1636476492573
entry_point_name: ''
experiment_id: '13'
lifecycle_stage: active
name: ''
run_id: c78c8e28be2a4394885c4a2b5aa79e56
run_uuid: c78c8e28be2a4394885c4a2b5aa79e56
source_name: ''
source_type: 4
source_version: ''
start_time: 1636476449105
status: 3
tags: []
user_id: root
