artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/6/11cf6ab28e054873acc618f685438796/artifacts
end_time: 1636406818022
entry_point_name: ''
experiment_id: '6'
lifecycle_stage: active
name: ''
run_id: 11cf6ab28e054873acc618f685438796
run_uuid: 11cf6ab28e054873acc618f685438796
source_name: ''
source_type: 4
source_version: ''
start_time: 1636406817996
status: 3
tags: []
user_id: root
