artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/0/535e07fab5aa4a0d89e1e992eaf595c2/artifacts
end_time: 1636311424532
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 535e07fab5aa4a0d89e1e992eaf595c2
run_uuid: 535e07fab5aa4a0d89e1e992eaf595c2
source_name: ''
source_type: 4
source_version: ''
start_time: 1636311424524
status: 3
tags: []
user_id: root
