artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/5/014ce4a7f686443a9d6bee7b913d971d/artifacts
end_time: 1636345248187
entry_point_name: ''
experiment_id: '5'
lifecycle_stage: active
name: ''
run_id: 014ce4a7f686443a9d6bee7b913d971d
run_uuid: 014ce4a7f686443a9d6bee7b913d971d
source_name: ''
source_type: 4
source_version: ''
start_time: 1636345248178
status: 3
tags: []
user_id: root
