artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/5/bcf2c4f1a7f64b4592ece03af2b86479/artifacts
end_time: 1636343006754
entry_point_name: ''
experiment_id: '5'
lifecycle_stage: active
name: ''
run_id: bcf2c4f1a7f64b4592ece03af2b86479
run_uuid: bcf2c4f1a7f64b4592ece03af2b86479
source_name: ''
source_type: 4
source_version: ''
start_time: 1636343006746
status: 3
tags: []
user_id: root
