artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/13/6d396dafff9445c781f485fe04b8b0e8/artifacts
end_time: 1636475974576
entry_point_name: ''
experiment_id: '13'
lifecycle_stage: active
name: ''
run_id: 6d396dafff9445c781f485fe04b8b0e8
run_uuid: 6d396dafff9445c781f485fe04b8b0e8
source_name: ''
source_type: 4
source_version: ''
start_time: 1636475974563
status: 3
tags: []
user_id: root
