artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/4/b1de9ceb93504e63ba7af637b776329e/artifacts
end_time: 1636342439547
entry_point_name: ''
experiment_id: '4'
lifecycle_stage: active
name: ''
run_id: b1de9ceb93504e63ba7af637b776329e
run_uuid: b1de9ceb93504e63ba7af637b776329e
source_name: ''
source_type: 4
source_version: ''
start_time: 1636342439537
status: 3
tags: []
user_id: root
