artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/6/06bef809af07489faed8e1856926787a/artifacts
end_time: 1636409451700
entry_point_name: ''
experiment_id: '6'
lifecycle_stage: active
name: ''
run_id: 06bef809af07489faed8e1856926787a
run_uuid: 06bef809af07489faed8e1856926787a
source_name: ''
source_type: 4
source_version: ''
start_time: 1636409333281
status: 3
tags: []
user_id: root
