artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/13/5bdfbdc1b491430292472792d35ac73a/artifacts
end_time: 1636475855484
entry_point_name: ''
experiment_id: '13'
lifecycle_stage: active
name: ''
run_id: 5bdfbdc1b491430292472792d35ac73a
run_uuid: 5bdfbdc1b491430292472792d35ac73a
source_name: ''
source_type: 4
source_version: ''
start_time: 1636475855471
status: 3
tags: []
user_id: root
