artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/2/ef66638e76704449b5aee9c9ddd6d2f0/artifacts
end_time: 1636330424313
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: ef66638e76704449b5aee9c9ddd6d2f0
run_uuid: ef66638e76704449b5aee9c9ddd6d2f0
source_name: ''
source_type: 4
source_version: ''
start_time: 1636330424306
status: 3
tags: []
user_id: root
