artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/7/75d9f462f145460aaad931aaae71abe6/artifacts
end_time: 1636413064811
entry_point_name: ''
experiment_id: '7'
lifecycle_stage: active
name: ''
run_id: 75d9f462f145460aaad931aaae71abe6
run_uuid: 75d9f462f145460aaad931aaae71abe6
source_name: ''
source_type: 4
source_version: ''
start_time: 1636413064801
status: 3
tags: []
user_id: root
