artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/2/c48bbd7ba1244645bb0403151400991c/artifacts
end_time: 1636332948273
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: c48bbd7ba1244645bb0403151400991c
run_uuid: c48bbd7ba1244645bb0403151400991c
source_name: ''
source_type: 4
source_version: ''
start_time: 1636332948266
status: 3
tags: []
user_id: root
