artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/6/793068ee778e4e0cb1690213c51248f4/artifacts
end_time: 1636404727992
entry_point_name: ''
experiment_id: '6'
lifecycle_stage: active
name: ''
run_id: 793068ee778e4e0cb1690213c51248f4
run_uuid: 793068ee778e4e0cb1690213c51248f4
source_name: ''
source_type: 4
source_version: ''
start_time: 1636404727982
status: 3
tags: []
user_id: root
