artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/4/2c517af857b34c94a215cdad4b64b0d2/artifacts
end_time: 1636342037241
entry_point_name: ''
experiment_id: '4'
lifecycle_stage: active
name: ''
run_id: 2c517af857b34c94a215cdad4b64b0d2
run_uuid: 2c517af857b34c94a215cdad4b64b0d2
source_name: ''
source_type: 4
source_version: ''
start_time: 1636342037230
status: 3
tags: []
user_id: root
