artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/6/7c0441821e3c40ebaa08f0e645e4f1ef/artifacts
end_time: 1636407631438
entry_point_name: ''
experiment_id: '6'
lifecycle_stage: active
name: ''
run_id: 7c0441821e3c40ebaa08f0e645e4f1ef
run_uuid: 7c0441821e3c40ebaa08f0e645e4f1ef
source_name: ''
source_type: 4
source_version: ''
start_time: 1636407631416
status: 3
tags: []
user_id: root
