artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/7/47c3a45c18d9437dab0c80d714d515d1/artifacts
end_time: 1636414438536
entry_point_name: ''
experiment_id: '7'
lifecycle_stage: active
name: ''
run_id: 47c3a45c18d9437dab0c80d714d515d1
run_uuid: 47c3a45c18d9437dab0c80d714d515d1
source_name: ''
source_type: 4
source_version: ''
start_time: 1636414438525
status: 3
tags: []
user_id: root
