artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/7/fa3eae5db470436dbeddb5f142f80568/artifacts
end_time: 1636415012321
entry_point_name: ''
experiment_id: '7'
lifecycle_stage: active
name: ''
run_id: fa3eae5db470436dbeddb5f142f80568
run_uuid: fa3eae5db470436dbeddb5f142f80568
source_name: ''
source_type: 4
source_version: ''
start_time: 1636415012311
status: 3
tags: []
user_id: root
