artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/4/edade8e985054fd0baed2f46406b6682/artifacts
end_time: 1636342248786
entry_point_name: ''
experiment_id: '4'
lifecycle_stage: active
name: ''
run_id: edade8e985054fd0baed2f46406b6682
run_uuid: edade8e985054fd0baed2f46406b6682
source_name: ''
source_type: 4
source_version: ''
start_time: 1636342248777
status: 3
tags: []
user_id: root
