artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/13/c36b6904de49418a805f94dcbaa2a48e/artifacts
end_time: 1636474575404
entry_point_name: ''
experiment_id: '13'
lifecycle_stage: active
name: ''
run_id: c36b6904de49418a805f94dcbaa2a48e
run_uuid: c36b6904de49418a805f94dcbaa2a48e
source_name: ''
source_type: 4
source_version: ''
start_time: 1636474575391
status: 3
tags: []
user_id: root
