artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/13/59365fd7671f4142899eac94f00cfb7c/artifacts
end_time: 1636476223611
entry_point_name: ''
experiment_id: '13'
lifecycle_stage: active
name: ''
run_id: 59365fd7671f4142899eac94f00cfb7c
run_uuid: 59365fd7671f4142899eac94f00cfb7c
source_name: ''
source_type: 4
source_version: ''
start_time: 1636476223598
status: 3
tags: []
user_id: root
