artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/2/3692f7391cc64676ae8ce1926abe2a29/artifacts
end_time: 1636329760967
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 3692f7391cc64676ae8ce1926abe2a29
run_uuid: 3692f7391cc64676ae8ce1926abe2a29
source_name: ''
source_type: 4
source_version: ''
start_time: 1636329760960
status: 3
tags: []
user_id: root
