artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/1/9aac18c57aaa4fa69753d9817dd2a1c9/artifacts
end_time: 1636324452211
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 9aac18c57aaa4fa69753d9817dd2a1c9
run_uuid: 9aac18c57aaa4fa69753d9817dd2a1c9
source_name: ''
source_type: 4
source_version: ''
start_time: 1636324452204
status: 3
tags: []
user_id: root
