artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/5/6e418f0c3f1c4a7c849c2d5455556eda/artifacts
end_time: 1636343134644
entry_point_name: ''
experiment_id: '5'
lifecycle_stage: active
name: ''
run_id: 6e418f0c3f1c4a7c849c2d5455556eda
run_uuid: 6e418f0c3f1c4a7c849c2d5455556eda
source_name: ''
source_type: 4
source_version: ''
start_time: 1636343134636
status: 3
tags: []
user_id: root
