artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/5/a729ccc34a9f4955897e1bdf354898b0/artifacts
end_time: 1636343556647
entry_point_name: ''
experiment_id: '5'
lifecycle_stage: active
name: ''
run_id: a729ccc34a9f4955897e1bdf354898b0
run_uuid: a729ccc34a9f4955897e1bdf354898b0
source_name: ''
source_type: 4
source_version: ''
start_time: 1636343556640
status: 3
tags: []
user_id: root
