artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/6/dc143fb24d68455db5076b18fe70c5c9/artifacts
end_time: 1636408680561
entry_point_name: ''
experiment_id: '6'
lifecycle_stage: active
name: ''
run_id: dc143fb24d68455db5076b18fe70c5c9
run_uuid: dc143fb24d68455db5076b18fe70c5c9
source_name: ''
source_type: 4
source_version: ''
start_time: 1636408680551
status: 3
tags: []
user_id: root
