artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/3/28cb6259a6f44191a69c4416f605023d/artifacts
end_time: 1636341691806
entry_point_name: ''
experiment_id: '3'
lifecycle_stage: active
name: ''
run_id: 28cb6259a6f44191a69c4416f605023d
run_uuid: 28cb6259a6f44191a69c4416f605023d
source_name: ''
source_type: 4
source_version: ''
start_time: 1636341651248
status: 3
tags: []
user_id: root
