artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/6/c107a4c74fa949d7bcaff1f926f229da/artifacts
end_time: 1636408979510
entry_point_name: ''
experiment_id: '6'
lifecycle_stage: active
name: ''
run_id: c107a4c74fa949d7bcaff1f926f229da
run_uuid: c107a4c74fa949d7bcaff1f926f229da
source_name: ''
source_type: 4
source_version: ''
start_time: 1636408979500
status: 3
tags: []
user_id: root
