artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/5/460f00ff3a914e088a09270dbe99bd93/artifacts
end_time: 1636346733802
entry_point_name: ''
experiment_id: '5'
lifecycle_stage: active
name: ''
run_id: 460f00ff3a914e088a09270dbe99bd93
run_uuid: 460f00ff3a914e088a09270dbe99bd93
source_name: ''
source_type: 4
source_version: ''
start_time: 1636346733792
status: 3
tags: []
user_id: root
