artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/13/cd09f7c3ab2f424fbd2698618fc053ab/artifacts
end_time: 1636473843591
entry_point_name: ''
experiment_id: '13'
lifecycle_stage: active
name: ''
run_id: cd09f7c3ab2f424fbd2698618fc053ab
run_uuid: cd09f7c3ab2f424fbd2698618fc053ab
source_name: ''
source_type: 4
source_version: ''
start_time: 1636473843577
status: 3
tags: []
user_id: root
