artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/5/2caf7684b162461aae57cd29e612b993/artifacts
end_time: 1636343483443
entry_point_name: ''
experiment_id: '5'
lifecycle_stage: active
name: ''
run_id: 2caf7684b162461aae57cd29e612b993
run_uuid: 2caf7684b162461aae57cd29e612b993
source_name: ''
source_type: 4
source_version: ''
start_time: 1636343483435
status: 3
tags: []
user_id: root
