artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/2/6d4a09e1d57949f4ada2b70e95f7da62/artifacts
end_time: 1636330090865
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 6d4a09e1d57949f4ada2b70e95f7da62
run_uuid: 6d4a09e1d57949f4ada2b70e95f7da62
source_name: ''
source_type: 4
source_version: ''
start_time: 1636330090856
status: 3
tags: []
user_id: root
