artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/5/558f2076881642d5980084ad1fbf3a5d/artifacts
end_time: 1636343338610
entry_point_name: ''
experiment_id: '5'
lifecycle_stage: active
name: ''
run_id: 558f2076881642d5980084ad1fbf3a5d
run_uuid: 558f2076881642d5980084ad1fbf3a5d
source_name: ''
source_type: 4
source_version: ''
start_time: 1636343338602
status: 3
tags: []
user_id: root
