artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/12/a5388c60701b4cb4b9128dc3328efa07/artifacts
end_time: 1636470418814
entry_point_name: ''
experiment_id: '12'
lifecycle_stage: active
name: ''
run_id: a5388c60701b4cb4b9128dc3328efa07
run_uuid: a5388c60701b4cb4b9128dc3328efa07
source_name: ''
source_type: 4
source_version: ''
start_time: 1636470418379
status: 4
tags: []
user_id: root
