artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/13/88eb9237e5f34f8db0b8d7147fb3090d/artifacts
end_time: 1636474136861
entry_point_name: ''
experiment_id: '13'
lifecycle_stage: active
name: ''
run_id: 88eb9237e5f34f8db0b8d7147fb3090d
run_uuid: 88eb9237e5f34f8db0b8d7147fb3090d
source_name: ''
source_type: 4
source_version: ''
start_time: 1636474136848
status: 3
tags: []
user_id: root
