artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/13/a92b42533b224c13874842c99a5a6fc7/artifacts
end_time: 1636476411615
entry_point_name: ''
experiment_id: '13'
lifecycle_stage: active
name: ''
run_id: a92b42533b224c13874842c99a5a6fc7
run_uuid: a92b42533b224c13874842c99a5a6fc7
source_name: ''
source_type: 4
source_version: ''
start_time: 1636476411601
status: 3
tags: []
user_id: root
