artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/2/83a5a1443b93435d8be5efce16f5fe77/artifacts
end_time: 1636333826393
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 83a5a1443b93435d8be5efce16f5fe77
run_uuid: 83a5a1443b93435d8be5efce16f5fe77
source_name: ''
source_type: 4
source_version: ''
start_time: 1636333826385
status: 3
tags: []
user_id: root
