artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/2/7a159bb0c07a45c99a27e64cf9da2325/artifacts
end_time: 1636329698949
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 7a159bb0c07a45c99a27e64cf9da2325
run_uuid: 7a159bb0c07a45c99a27e64cf9da2325
source_name: ''
source_type: 4
source_version: ''
start_time: 1636329698941
status: 3
tags: []
user_id: root
