artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/13/c5007522f24045f1b9890a9aac1b9ae5/artifacts
end_time: 1636475443666
entry_point_name: ''
experiment_id: '13'
lifecycle_stage: active
name: ''
run_id: c5007522f24045f1b9890a9aac1b9ae5
run_uuid: c5007522f24045f1b9890a9aac1b9ae5
source_name: ''
source_type: 4
source_version: ''
start_time: 1636475443653
status: 3
tags: []
user_id: root
