artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/9/22ffd7739cf34703975e5030a4cf45f5/artifacts
end_time: 1636433345576
entry_point_name: ''
experiment_id: '9'
lifecycle_stage: active
name: ''
run_id: 22ffd7739cf34703975e5030a4cf45f5
run_uuid: 22ffd7739cf34703975e5030a4cf45f5
source_name: ''
source_type: 4
source_version: ''
start_time: 1636432936459
status: 3
tags: []
user_id: root
