artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/13/921972b97bcc435bb98bcf2a00943f6d/artifacts
end_time: 1636476077325
entry_point_name: ''
experiment_id: '13'
lifecycle_stage: active
name: ''
run_id: 921972b97bcc435bb98bcf2a00943f6d
run_uuid: 921972b97bcc435bb98bcf2a00943f6d
source_name: ''
source_type: 4
source_version: ''
start_time: 1636476077311
status: 3
tags: []
user_id: root
