artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/2/c748269b6e56418fb927610b24aa520d/artifacts
end_time: 1636334359385
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: c748269b6e56418fb927610b24aa520d
run_uuid: c748269b6e56418fb927610b24aa520d
source_name: ''
source_type: 4
source_version: ''
start_time: 1636334359377
status: 3
tags: []
user_id: root
