artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/5/8ae54267b35743019099f0be7a71b367/artifacts
end_time: 1636346481509
entry_point_name: ''
experiment_id: '5'
lifecycle_stage: active
name: ''
run_id: 8ae54267b35743019099f0be7a71b367
run_uuid: 8ae54267b35743019099f0be7a71b367
source_name: ''
source_type: 4
source_version: ''
start_time: 1636346481501
status: 3
tags: []
user_id: root
