artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/11/d5cf085689bd4655bce3cfba9dc344f3/artifacts
end_time: 1636435898737
entry_point_name: ''
experiment_id: '11'
lifecycle_stage: active
name: ''
run_id: d5cf085689bd4655bce3cfba9dc344f3
run_uuid: d5cf085689bd4655bce3cfba9dc344f3
source_name: ''
source_type: 4
source_version: ''
start_time: 1636435898726
status: 3
tags: []
user_id: root
