artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/2/24c2c61fef5d47a48d0e023891ec3b62/artifacts
end_time: 1636338656156
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 24c2c61fef5d47a48d0e023891ec3b62
run_uuid: 24c2c61fef5d47a48d0e023891ec3b62
source_name: ''
source_type: 4
source_version: ''
start_time: 1636338656148
status: 3
tags: []
user_id: root
