artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/5/bea5969ad49a4469b208419dfc68346d/artifacts
end_time: 1636345157144
entry_point_name: ''
experiment_id: '5'
lifecycle_stage: active
name: ''
run_id: bea5969ad49a4469b208419dfc68346d
run_uuid: bea5969ad49a4469b208419dfc68346d
source_name: ''
source_type: 4
source_version: ''
start_time: 1636345157127
status: 3
tags: []
user_id: root
