artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/2/c514a7aa5ec44eddbceadcd10daa0833/artifacts
end_time: 1636329050392
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: c514a7aa5ec44eddbceadcd10daa0833
run_uuid: c514a7aa5ec44eddbceadcd10daa0833
source_name: ''
source_type: 4
source_version: ''
start_time: 1636329050383
status: 3
tags: []
user_id: root
