artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/12/04ec364bc2724987b979620b94e90ec7/artifacts
end_time: 1636468145171
entry_point_name: ''
experiment_id: '12'
lifecycle_stage: active
name: ''
run_id: 04ec364bc2724987b979620b94e90ec7
run_uuid: 04ec364bc2724987b979620b94e90ec7
source_name: ''
source_type: 4
source_version: ''
start_time: 1636468132384
status: 3
tags: []
user_id: root
