artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/13/69202ae8dd064309b7dd9f5a631a3efa/artifacts
end_time: 1636475900940
entry_point_name: ''
experiment_id: '13'
lifecycle_stage: active
name: ''
run_id: 69202ae8dd064309b7dd9f5a631a3efa
run_uuid: 69202ae8dd064309b7dd9f5a631a3efa
source_name: ''
source_type: 4
source_version: ''
start_time: 1636475900927
status: 3
tags: []
user_id: root
