artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/13/63012430dd6a4746b03d92d828a365b3/artifacts
end_time: 1636475791396
entry_point_name: ''
experiment_id: '13'
lifecycle_stage: active
name: ''
run_id: 63012430dd6a4746b03d92d828a365b3
run_uuid: 63012430dd6a4746b03d92d828a365b3
source_name: ''
source_type: 4
source_version: ''
start_time: 1636475791382
status: 3
tags: []
user_id: root
