artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/2/7f8f652101274b53b887a079bd16ebaf/artifacts
end_time: 1636337321847
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 7f8f652101274b53b887a079bd16ebaf
run_uuid: 7f8f652101274b53b887a079bd16ebaf
source_name: ''
source_type: 4
source_version: ''
start_time: 1636337321840
status: 3
tags: []
user_id: root
