artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/5/068c7035edbe4911ac5f086472d8a8b7/artifacts
end_time: 1636344541254
entry_point_name: ''
experiment_id: '5'
lifecycle_stage: active
name: ''
run_id: 068c7035edbe4911ac5f086472d8a8b7
run_uuid: 068c7035edbe4911ac5f086472d8a8b7
source_name: ''
source_type: 4
source_version: ''
start_time: 1636344541246
status: 3
tags: []
user_id: root
