artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/5/796ef930d9e643bab12dda8b8111ba7f/artifacts
end_time: 1636343700938
entry_point_name: ''
experiment_id: '5'
lifecycle_stage: active
name: ''
run_id: 796ef930d9e643bab12dda8b8111ba7f
run_uuid: 796ef930d9e643bab12dda8b8111ba7f
source_name: ''
source_type: 4
source_version: ''
start_time: 1636343700930
status: 3
tags: []
user_id: root
