artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/5/b7ae5c5fede848f587ef0fa702f091bb/artifacts
end_time: 1636344083033
entry_point_name: ''
experiment_id: '5'
lifecycle_stage: active
name: ''
run_id: b7ae5c5fede848f587ef0fa702f091bb
run_uuid: b7ae5c5fede848f587ef0fa702f091bb
source_name: ''
source_type: 4
source_version: ''
start_time: 1636344083025
status: 3
tags: []
user_id: root
