artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/2/229e88226e894c148cc4d4350e3cc868/artifacts
end_time: 1636339408382
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 229e88226e894c148cc4d4350e3cc868
run_uuid: 229e88226e894c148cc4d4350e3cc868
source_name: ''
source_type: 4
source_version: ''
start_time: 1636339408374
status: 3
tags: []
user_id: root
