artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/6/4d7df817586c4f4b83588b3e4496555d/artifacts
end_time: 1636405059965
entry_point_name: ''
experiment_id: '6'
lifecycle_stage: active
name: ''
run_id: 4d7df817586c4f4b83588b3e4496555d
run_uuid: 4d7df817586c4f4b83588b3e4496555d
source_name: ''
source_type: 4
source_version: ''
start_time: 1636405059954
status: 3
tags: []
user_id: root
