artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/13/88a401c03841426bbca2717a062f22c5/artifacts
end_time: 1636474364384
entry_point_name: ''
experiment_id: '13'
lifecycle_stage: active
name: ''
run_id: 88a401c03841426bbca2717a062f22c5
run_uuid: 88a401c03841426bbca2717a062f22c5
source_name: ''
source_type: 4
source_version: ''
start_time: 1636474364370
status: 3
tags: []
user_id: root
