artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/13/120e4d0d57ea406985db4da6db973436/artifacts
end_time: 1636473656761
entry_point_name: ''
experiment_id: '13'
lifecycle_stage: active
name: ''
run_id: 120e4d0d57ea406985db4da6db973436
run_uuid: 120e4d0d57ea406985db4da6db973436
source_name: ''
source_type: 4
source_version: ''
start_time: 1636473656748
status: 3
tags: []
user_id: root
