artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/4/bba2971ba2ba441580d54e3f6405c684/artifacts
end_time: 1636342099872
entry_point_name: ''
experiment_id: '4'
lifecycle_stage: active
name: ''
run_id: bba2971ba2ba441580d54e3f6405c684
run_uuid: bba2971ba2ba441580d54e3f6405c684
source_name: ''
source_type: 4
source_version: ''
start_time: 1636342099864
status: 3
tags: []
user_id: root
