artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/7/879fbe0059304454badaf0af43bbaad3/artifacts
end_time: 1636414636343
entry_point_name: ''
experiment_id: '7'
lifecycle_stage: active
name: ''
run_id: 879fbe0059304454badaf0af43bbaad3
run_uuid: 879fbe0059304454badaf0af43bbaad3
source_name: ''
source_type: 4
source_version: ''
start_time: 1636414636332
status: 3
tags: []
user_id: root
