artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/8/31e09239799c4a22837a1ac4a22bb92f/artifacts
end_time: 1636418682554
entry_point_name: ''
experiment_id: '8'
lifecycle_stage: active
name: ''
run_id: 31e09239799c4a22837a1ac4a22bb92f
run_uuid: 31e09239799c4a22837a1ac4a22bb92f
source_name: ''
source_type: 4
source_version: ''
start_time: 1636418673875
status: 3
tags: []
user_id: root
