artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/7/d6aa0d192af64b82971907294edfedbb/artifacts
end_time: 1636414846177
entry_point_name: ''
experiment_id: '7'
lifecycle_stage: active
name: ''
run_id: d6aa0d192af64b82971907294edfedbb
run_uuid: d6aa0d192af64b82971907294edfedbb
source_name: ''
source_type: 4
source_version: ''
start_time: 1636414846167
status: 3
tags: []
user_id: root
