artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/13/029ed99f76d24872b9b6f53214e03c72/artifacts
end_time: 1636476449029
entry_point_name: ''
experiment_id: '13'
lifecycle_stage: active
name: ''
run_id: 029ed99f76d24872b9b6f53214e03c72
run_uuid: 029ed99f76d24872b9b6f53214e03c72
source_name: ''
source_type: 4
source_version: ''
start_time: 1636476449016
status: 3
tags: []
user_id: root
