artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/7/5da90a3232934bce932ab6a8d5be3a79/artifacts
end_time: 1636414332651
entry_point_name: ''
experiment_id: '7'
lifecycle_stage: active
name: ''
run_id: 5da90a3232934bce932ab6a8d5be3a79
run_uuid: 5da90a3232934bce932ab6a8d5be3a79
source_name: ''
source_type: 4
source_version: ''
start_time: 1636414332641
status: 3
tags: []
user_id: root
