artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/13/eda9f1f603b5409ba83df8d30b870fea/artifacts
end_time: 1636474452851
entry_point_name: ''
experiment_id: '13'
lifecycle_stage: active
name: ''
run_id: eda9f1f603b5409ba83df8d30b870fea
run_uuid: eda9f1f603b5409ba83df8d30b870fea
source_name: ''
source_type: 4
source_version: ''
start_time: 1636474452838
status: 3
tags: []
user_id: root
