artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/13/21eda463e8094fdcb1c7d265f12d48d9/artifacts
end_time: 1636475625914
entry_point_name: ''
experiment_id: '13'
lifecycle_stage: active
name: ''
run_id: 21eda463e8094fdcb1c7d265f12d48d9
run_uuid: 21eda463e8094fdcb1c7d265f12d48d9
source_name: ''
source_type: 4
source_version: ''
start_time: 1636475625901
status: 3
tags: []
user_id: root
