artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/5/d1942c278aeb4517a4d9de25b567edde/artifacts
end_time: 1636343795640
entry_point_name: ''
experiment_id: '5'
lifecycle_stage: active
name: ''
run_id: d1942c278aeb4517a4d9de25b567edde
run_uuid: d1942c278aeb4517a4d9de25b567edde
source_name: ''
source_type: 4
source_version: ''
start_time: 1636343795633
status: 3
tags: []
user_id: root
