artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/5/ebdc868b459c44c797ef20da5046ac54/artifacts
end_time: 1636346389810
entry_point_name: ''
experiment_id: '5'
lifecycle_stage: active
name: ''
run_id: ebdc868b459c44c797ef20da5046ac54
run_uuid: ebdc868b459c44c797ef20da5046ac54
source_name: ''
source_type: 4
source_version: ''
start_time: 1636346389794
status: 3
tags: []
user_id: root
