artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/5/b95d3b71c61c44d98c2a19c2d4f81dfc/artifacts
end_time: 1636345396448
entry_point_name: ''
experiment_id: '5'
lifecycle_stage: active
name: ''
run_id: b95d3b71c61c44d98c2a19c2d4f81dfc
run_uuid: b95d3b71c61c44d98c2a19c2d4f81dfc
source_name: ''
source_type: 4
source_version: ''
start_time: 1636345396440
status: 3
tags: []
user_id: root
