artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/5/0c14ed612a634b52be0cd160375ace95/artifacts
end_time: 1636346038555
entry_point_name: ''
experiment_id: '5'
lifecycle_stage: active
name: ''
run_id: 0c14ed612a634b52be0cd160375ace95
run_uuid: 0c14ed612a634b52be0cd160375ace95
source_name: ''
source_type: 4
source_version: ''
start_time: 1636346038546
status: 3
tags: []
user_id: root
