artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/9/0ba6e80261d54eccb0f5343092de5122/artifacts
end_time: 1636420712340
entry_point_name: ''
experiment_id: '9'
lifecycle_stage: active
name: ''
run_id: 0ba6e80261d54eccb0f5343092de5122
run_uuid: 0ba6e80261d54eccb0f5343092de5122
source_name: ''
source_type: 4
source_version: ''
start_time: 1636420677634
status: 3
tags: []
user_id: root
