artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/2/900304fe8330442d889cba62f141aa6e/artifacts
end_time: 1636336394688
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 900304fe8330442d889cba62f141aa6e
run_uuid: 900304fe8330442d889cba62f141aa6e
source_name: ''
source_type: 4
source_version: ''
start_time: 1636336394681
status: 3
tags: []
user_id: root
