artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/5/982966297aa74bc1b216977fcec7a336/artifacts
end_time: 1636344364250
entry_point_name: ''
experiment_id: '5'
lifecycle_stage: active
name: ''
run_id: 982966297aa74bc1b216977fcec7a336
run_uuid: 982966297aa74bc1b216977fcec7a336
source_name: ''
source_type: 4
source_version: ''
start_time: 1636344364242
status: 3
tags: []
user_id: root
