artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/2/0f06286bf73a472ebae1c95bdec32f46/artifacts
end_time: 1636329620905
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 0f06286bf73a472ebae1c95bdec32f46
run_uuid: 0f06286bf73a472ebae1c95bdec32f46
source_name: ''
source_type: 4
source_version: ''
start_time: 1636329620897
status: 3
tags: []
user_id: root
