artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/7/229292cf05c9487790479e6e0f640d6a/artifacts
end_time: 1636414242102
entry_point_name: ''
experiment_id: '7'
lifecycle_stage: active
name: ''
run_id: 229292cf05c9487790479e6e0f640d6a
run_uuid: 229292cf05c9487790479e6e0f640d6a
source_name: ''
source_type: 4
source_version: ''
start_time: 1636414242092
status: 3
tags: []
user_id: root
