artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/9/ac79610eefc54e9ab3d615c3d043ba70/artifacts
end_time: 1636420993215
entry_point_name: ''
experiment_id: '9'
lifecycle_stage: active
name: ''
run_id: ac79610eefc54e9ab3d615c3d043ba70
run_uuid: ac79610eefc54e9ab3d615c3d043ba70
source_name: ''
source_type: 4
source_version: ''
start_time: 1636420972445
status: 3
tags: []
user_id: root
