artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/8/45eb362fe4174836af07287079a16a81/artifacts
end_time: 1636417101503
entry_point_name: ''
experiment_id: '8'
lifecycle_stage: active
name: ''
run_id: 45eb362fe4174836af07287079a16a81
run_uuid: 45eb362fe4174836af07287079a16a81
source_name: ''
source_type: 4
source_version: ''
start_time: 1636417098502
status: 4
tags: []
user_id: root
