artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/13/0b766702d5104ec299434cee732ff132/artifacts
end_time: 1636476183815
entry_point_name: ''
experiment_id: '13'
lifecycle_stage: active
name: ''
run_id: 0b766702d5104ec299434cee732ff132
run_uuid: 0b766702d5104ec299434cee732ff132
source_name: ''
source_type: 4
source_version: ''
start_time: 1636476183801
status: 3
tags: []
user_id: root
