artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/10/3598ecc6762b4a55b2e6531221aed640/artifacts
end_time: 1636432097836
entry_point_name: ''
experiment_id: '10'
lifecycle_stage: active
name: ''
run_id: 3598ecc6762b4a55b2e6531221aed640
run_uuid: 3598ecc6762b4a55b2e6531221aed640
source_name: ''
source_type: 4
source_version: ''
start_time: 1636431990803
status: 3
tags: []
user_id: root
