artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/2/84be395347854f999611c10189dfcf02/artifacts
end_time: 1636335269805
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 84be395347854f999611c10189dfcf02
run_uuid: 84be395347854f999611c10189dfcf02
source_name: ''
source_type: 4
source_version: ''
start_time: 1636335269797
status: 3
tags: []
user_id: root
