artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/7/bea2ef9b62e74ad88f4a0dc09436c8a5/artifacts
end_time: 1636412111896
entry_point_name: ''
experiment_id: '7'
lifecycle_stage: active
name: ''
run_id: bea2ef9b62e74ad88f4a0dc09436c8a5
run_uuid: bea2ef9b62e74ad88f4a0dc09436c8a5
source_name: ''
source_type: 4
source_version: ''
start_time: 1636412111887
status: 3
tags: []
user_id: root
