artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/7/3413251238a94eed9163ee5458fa67a4/artifacts
end_time: 1636413495239
entry_point_name: ''
experiment_id: '7'
lifecycle_stage: active
name: ''
run_id: 3413251238a94eed9163ee5458fa67a4
run_uuid: 3413251238a94eed9163ee5458fa67a4
source_name: ''
source_type: 4
source_version: ''
start_time: 1636413495229
status: 3
tags: []
user_id: root
