artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/13/00b51b32505d45a7a466de222b63a818/artifacts
end_time: 1636476043317
entry_point_name: ''
experiment_id: '13'
lifecycle_stage: active
name: ''
run_id: 00b51b32505d45a7a466de222b63a818
run_uuid: 00b51b32505d45a7a466de222b63a818
source_name: ''
source_type: 4
source_version: ''
start_time: 1636476043304
status: 3
tags: []
user_id: root
