artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/8/e230aa04eb61430cb9f97609643a2637/artifacts
end_time: 1636417385446
entry_point_name: ''
experiment_id: '8'
lifecycle_stage: active
name: ''
run_id: e230aa04eb61430cb9f97609643a2637
run_uuid: e230aa04eb61430cb9f97609643a2637
source_name: ''
source_type: 4
source_version: ''
start_time: 1636417382432
status: 4
tags: []
user_id: root
