artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/2/eb2645fb460e4f4bbca2f5a862fdac3e/artifacts
end_time: 1636339537897
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: eb2645fb460e4f4bbca2f5a862fdac3e
run_uuid: eb2645fb460e4f4bbca2f5a862fdac3e
source_name: ''
source_type: 4
source_version: ''
start_time: 1636339537889
status: 3
tags: []
user_id: root
