artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/8/21adaf35c7f84055acb828603de16295/artifacts
end_time: 1636417274615
entry_point_name: ''
experiment_id: '8'
lifecycle_stage: active
name: ''
run_id: 21adaf35c7f84055acb828603de16295
run_uuid: 21adaf35c7f84055acb828603de16295
source_name: ''
source_type: 4
source_version: ''
start_time: 1636417271588
status: 4
tags: []
user_id: root
