artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/6/aaffafbf8fd646379bd7ea61cecf9158/artifacts
end_time: 1636405205289
entry_point_name: ''
experiment_id: '6'
lifecycle_stage: active
name: ''
run_id: aaffafbf8fd646379bd7ea61cecf9158
run_uuid: aaffafbf8fd646379bd7ea61cecf9158
source_name: ''
source_type: 4
source_version: ''
start_time: 1636405205279
status: 3
tags: []
user_id: root
