artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/2/4f17b85a0df747f789ecbad291f59140/artifacts
end_time: 1636339670390
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 4f17b85a0df747f789ecbad291f59140
run_uuid: 4f17b85a0df747f789ecbad291f59140
source_name: ''
source_type: 4
source_version: ''
start_time: 1636339670366
status: 3
tags: []
user_id: root
