artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/2/ff2fde91a4fd4d9083d59f51ff45a981/artifacts
end_time: 1636337595187
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: ff2fde91a4fd4d9083d59f51ff45a981
run_uuid: ff2fde91a4fd4d9083d59f51ff45a981
source_name: ''
source_type: 4
source_version: ''
start_time: 1636337595179
status: 3
tags: []
user_id: root
