artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/13/e24b89a89041452b9fe5a290a93cc0fb/artifacts
end_time: 1636475821255
entry_point_name: ''
experiment_id: '13'
lifecycle_stage: active
name: ''
run_id: e24b89a89041452b9fe5a290a93cc0fb
run_uuid: e24b89a89041452b9fe5a290a93cc0fb
source_name: ''
source_type: 4
source_version: ''
start_time: 1636475821241
status: 3
tags: []
user_id: root
