artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/6/370a17b195de41f1b184fb5b9c8cc693/artifacts
end_time: 1636408000468
entry_point_name: ''
experiment_id: '6'
lifecycle_stage: active
name: ''
run_id: 370a17b195de41f1b184fb5b9c8cc693
run_uuid: 370a17b195de41f1b184fb5b9c8cc693
source_name: ''
source_type: 4
source_version: ''
start_time: 1636408000456
status: 3
tags: []
user_id: root
