artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/4/152cdb5d40aa43f6898b2089f4b6ea87/artifacts
end_time: 1636342480811
entry_point_name: ''
experiment_id: '4'
lifecycle_stage: active
name: ''
run_id: 152cdb5d40aa43f6898b2089f4b6ea87
run_uuid: 152cdb5d40aa43f6898b2089f4b6ea87
source_name: ''
source_type: 4
source_version: ''
start_time: 1636342439614
status: 3
tags: []
user_id: root
