artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/14/3f2f6a75f6ab4b0bb7da52fad636d26c/artifacts
end_time: 1638144088233
entry_point_name: ''
experiment_id: '14'
lifecycle_stage: active
name: ''
run_id: 3f2f6a75f6ab4b0bb7da52fad636d26c
run_uuid: 3f2f6a75f6ab4b0bb7da52fad636d26c
source_name: ''
source_type: 4
source_version: ''
start_time: 1638143892579
status: 4
tags: []
user_id: kaushik
