artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/7/965ad6a9d50641ffbece7ca33e490452/artifacts
end_time: 1636414148531
entry_point_name: ''
experiment_id: '7'
lifecycle_stage: active
name: ''
run_id: 965ad6a9d50641ffbece7ca33e490452
run_uuid: 965ad6a9d50641ffbece7ca33e490452
source_name: ''
source_type: 4
source_version: ''
start_time: 1636414148522
status: 3
tags: []
user_id: root
