artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/8/581b9c81b1674ceb872176b5c46f1007/artifacts
end_time: 1636417014903
entry_point_name: ''
experiment_id: '8'
lifecycle_stage: active
name: ''
run_id: 581b9c81b1674ceb872176b5c46f1007
run_uuid: 581b9c81b1674ceb872176b5c46f1007
source_name: ''
source_type: 4
source_version: ''
start_time: 1636416988727
status: 4
tags: []
user_id: root
