artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/2/42e2cd51136046a7a7a145301ffe60f2/artifacts
end_time: 1636332586611
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 42e2cd51136046a7a7a145301ffe60f2
run_uuid: 42e2cd51136046a7a7a145301ffe60f2
source_name: ''
source_type: 4
source_version: ''
start_time: 1636332586604
status: 3
tags: []
user_id: root
