artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/7/9344eaa745d447568ea5b1478dcca491/artifacts
end_time: 1636410623880
entry_point_name: ''
experiment_id: '7'
lifecycle_stage: active
name: ''
run_id: 9344eaa745d447568ea5b1478dcca491
run_uuid: 9344eaa745d447568ea5b1478dcca491
source_name: ''
source_type: 4
source_version: ''
start_time: 1636410623870
status: 3
tags: []
user_id: root
