artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/14/a6a7687add1b46c390096ee4925e14f5/artifacts
end_time: 1638144917525
entry_point_name: ''
experiment_id: '14'
lifecycle_stage: active
name: ''
run_id: a6a7687add1b46c390096ee4925e14f5
run_uuid: a6a7687add1b46c390096ee4925e14f5
source_name: ''
source_type: 4
source_version: ''
start_time: 1638144113226
status: 4
tags: []
user_id: kaushik
