artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/5/9526378d9a3940b4a53a0688dfebd3f7/artifacts
end_time: 1636345326477
entry_point_name: ''
experiment_id: '5'
lifecycle_stage: active
name: ''
run_id: 9526378d9a3940b4a53a0688dfebd3f7
run_uuid: 9526378d9a3940b4a53a0688dfebd3f7
source_name: ''
source_type: 4
source_version: ''
start_time: 1636345326469
status: 3
tags: []
user_id: root
