artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/2/67c9d88bc6784880a1fc5564db9c637f/artifacts
end_time: 1636339962295
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 67c9d88bc6784880a1fc5564db9c637f
run_uuid: 67c9d88bc6784880a1fc5564db9c637f
source_name: ''
source_type: 4
source_version: ''
start_time: 1636339962287
status: 3
tags: []
user_id: root
