artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/13/94227f9034804a71996e59a7ffe4ef4f/artifacts
end_time: 1636476146187
entry_point_name: ''
experiment_id: '13'
lifecycle_stage: active
name: ''
run_id: 94227f9034804a71996e59a7ffe4ef4f
run_uuid: 94227f9034804a71996e59a7ffe4ef4f
source_name: ''
source_type: 4
source_version: ''
start_time: 1636476146172
status: 3
tags: []
user_id: root
