artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/7/255355ece0174cf8bb56129deb139c9f/artifacts
end_time: 1636412821743
entry_point_name: ''
experiment_id: '7'
lifecycle_stage: active
name: ''
run_id: 255355ece0174cf8bb56129deb139c9f
run_uuid: 255355ece0174cf8bb56129deb139c9f
source_name: ''
source_type: 4
source_version: ''
start_time: 1636412821733
status: 3
tags: []
user_id: root
