artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/5/741d584255d04d6baa70b0c7839124aa/artifacts
end_time: 1636347210194
entry_point_name: ''
experiment_id: '5'
lifecycle_stage: active
name: ''
run_id: 741d584255d04d6baa70b0c7839124aa
run_uuid: 741d584255d04d6baa70b0c7839124aa
source_name: ''
source_type: 4
source_version: ''
start_time: 1636347118366
status: 3
tags: []
user_id: root
