artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/6/2c342665cdab4eada924abcb41677094/artifacts
end_time: 1636406118147
entry_point_name: ''
experiment_id: '6'
lifecycle_stage: active
name: ''
run_id: 2c342665cdab4eada924abcb41677094
run_uuid: 2c342665cdab4eada924abcb41677094
source_name: ''
source_type: 4
source_version: ''
start_time: 1636406118137
status: 3
tags: []
user_id: root
