artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/5/22dbaa151102419cb41105777b47b157/artifacts
end_time: 1636345891110
entry_point_name: ''
experiment_id: '5'
lifecycle_stage: active
name: ''
run_id: 22dbaa151102419cb41105777b47b157
run_uuid: 22dbaa151102419cb41105777b47b157
source_name: ''
source_type: 4
source_version: ''
start_time: 1636345891102
status: 3
tags: []
user_id: root
