artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/2/f3f535cd46f34a279c8e2b73ad1eeaf1/artifacts
end_time: 1636332174769
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: f3f535cd46f34a279c8e2b73ad1eeaf1
run_uuid: f3f535cd46f34a279c8e2b73ad1eeaf1
source_name: ''
source_type: 4
source_version: ''
start_time: 1636332174762
status: 3
tags: []
user_id: root
