artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/6/1683e75b937c422ab6ac2b61798da56a/artifacts
end_time: 1636408220892
entry_point_name: ''
experiment_id: '6'
lifecycle_stage: active
name: ''
run_id: 1683e75b937c422ab6ac2b61798da56a
run_uuid: 1683e75b937c422ab6ac2b61798da56a
source_name: ''
source_type: 4
source_version: ''
start_time: 1636408220881
status: 3
tags: []
user_id: root
