artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/7/a519ec95493e4b3eaa3c427ba5e5562a/artifacts
end_time: 1636413401982
entry_point_name: ''
experiment_id: '7'
lifecycle_stage: active
name: ''
run_id: a519ec95493e4b3eaa3c427ba5e5562a
run_uuid: a519ec95493e4b3eaa3c427ba5e5562a
source_name: ''
source_type: 4
source_version: ''
start_time: 1636413401972
status: 3
tags: []
user_id: root
