artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/3/c9d7045721f04846b35e04977c835f5c/artifacts
end_time: 1636341651185
entry_point_name: ''
experiment_id: '3'
lifecycle_stage: active
name: ''
run_id: c9d7045721f04846b35e04977c835f5c
run_uuid: c9d7045721f04846b35e04977c835f5c
source_name: ''
source_type: 4
source_version: ''
start_time: 1636341651177
status: 3
tags: []
user_id: root
