artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/2/527ef5cd35bb44d7aad226db3a171458/artifacts
end_time: 1636336122161
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 527ef5cd35bb44d7aad226db3a171458
run_uuid: 527ef5cd35bb44d7aad226db3a171458
source_name: ''
source_type: 4
source_version: ''
start_time: 1636336122153
status: 3
tags: []
user_id: root
