artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/7/93f806be31074e5fb18daff4c6975a30/artifacts
end_time: 1636415879015
entry_point_name: ''
experiment_id: '7'
lifecycle_stage: active
name: ''
run_id: 93f806be31074e5fb18daff4c6975a30
run_uuid: 93f806be31074e5fb18daff4c6975a30
source_name: ''
source_type: 4
source_version: ''
start_time: 1636415798226
status: 3
tags: []
user_id: root
