artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/5/4577b1106b63430cb44cbb8e2c9ccb4c/artifacts
end_time: 1636344276813
entry_point_name: ''
experiment_id: '5'
lifecycle_stage: active
name: ''
run_id: 4577b1106b63430cb44cbb8e2c9ccb4c
run_uuid: 4577b1106b63430cb44cbb8e2c9ccb4c
source_name: ''
source_type: 4
source_version: ''
start_time: 1636344276806
status: 3
tags: []
user_id: root
