artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/8/fc9ad17feed4454caeb226bc6ccaadc4/artifacts
end_time: 1636417168299
entry_point_name: ''
experiment_id: '8'
lifecycle_stage: active
name: ''
run_id: fc9ad17feed4454caeb226bc6ccaadc4
run_uuid: fc9ad17feed4454caeb226bc6ccaadc4
source_name: ''
source_type: 4
source_version: ''
start_time: 1636417165286
status: 4
tags: []
user_id: root
