artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/6/3d51919bca8d48f7b0ec70e2ed6309be/artifacts
end_time: 1636405854250
entry_point_name: ''
experiment_id: '6'
lifecycle_stage: active
name: ''
run_id: 3d51919bca8d48f7b0ec70e2ed6309be
run_uuid: 3d51919bca8d48f7b0ec70e2ed6309be
source_name: ''
source_type: 4
source_version: ''
start_time: 1636405854240
status: 3
tags: []
user_id: root
