artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/7/e39b95cbfecd4656858fb1ebea557416/artifacts
end_time: 1636415595609
entry_point_name: ''
experiment_id: '7'
lifecycle_stage: active
name: ''
run_id: e39b95cbfecd4656858fb1ebea557416
run_uuid: e39b95cbfecd4656858fb1ebea557416
source_name: ''
source_type: 4
source_version: ''
start_time: 1636415595599
status: 3
tags: []
user_id: root
