artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/2/f48693711a4c4dd48169b099ae1754cc/artifacts
end_time: 1636331934652
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: f48693711a4c4dd48169b099ae1754cc
run_uuid: f48693711a4c4dd48169b099ae1754cc
source_name: ''
source_type: 4
source_version: ''
start_time: 1636331934644
status: 3
tags: []
user_id: root
