artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/5/4eb18d2d756548f6807678dff9f0844a/artifacts
end_time: 1636346656295
entry_point_name: ''
experiment_id: '5'
lifecycle_stage: active
name: ''
run_id: 4eb18d2d756548f6807678dff9f0844a
run_uuid: 4eb18d2d756548f6807678dff9f0844a
source_name: ''
source_type: 4
source_version: ''
start_time: 1636346656287
status: 3
tags: []
user_id: root
