artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/9/401982229c5b45c7aba638d97014b53b/artifacts
end_time: 1636421237280
entry_point_name: ''
experiment_id: '9'
lifecycle_stage: active
name: ''
run_id: 401982229c5b45c7aba638d97014b53b
run_uuid: 401982229c5b45c7aba638d97014b53b
source_name: ''
source_type: 4
source_version: ''
start_time: 1636421224575
status: 3
tags: []
user_id: root
