artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/2/c91f7a64d9324665a3191fea5a75ae0d/artifacts
end_time: 1636339044763
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: c91f7a64d9324665a3191fea5a75ae0d
run_uuid: c91f7a64d9324665a3191fea5a75ae0d
source_name: ''
source_type: 4
source_version: ''
start_time: 1636339044754
status: 3
tags: []
user_id: root
