artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/13/0ec9e0f492f74fd7b130e9e05807d12a/artifacts
end_time: 1636475507097
entry_point_name: ''
experiment_id: '13'
lifecycle_stage: active
name: ''
run_id: 0ec9e0f492f74fd7b130e9e05807d12a
run_uuid: 0ec9e0f492f74fd7b130e9e05807d12a
source_name: ''
source_type: 4
source_version: ''
start_time: 1636475507084
status: 3
tags: []
user_id: root
