artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/7/6ce69e1588e7438b86286669f314d3e3/artifacts
end_time: 1636412752899
entry_point_name: ''
experiment_id: '7'
lifecycle_stage: active
name: ''
run_id: 6ce69e1588e7438b86286669f314d3e3
run_uuid: 6ce69e1588e7438b86286669f314d3e3
source_name: ''
source_type: 4
source_version: ''
start_time: 1636412752888
status: 3
tags: []
user_id: root
