artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/6/24f05e4c608a48eb931a5c2fd6c45c3f/artifacts
end_time: 1636404819098
entry_point_name: ''
experiment_id: '6'
lifecycle_stage: active
name: ''
run_id: 24f05e4c608a48eb931a5c2fd6c45c3f
run_uuid: 24f05e4c608a48eb931a5c2fd6c45c3f
source_name: ''
source_type: 4
source_version: ''
start_time: 1636404819087
status: 3
tags: []
user_id: root
