artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/5/b55a250368c745ce93d8f6385a5b052a/artifacts
end_time: 1636344866314
entry_point_name: ''
experiment_id: '5'
lifecycle_stage: active
name: ''
run_id: b55a250368c745ce93d8f6385a5b052a
run_uuid: b55a250368c745ce93d8f6385a5b052a
source_name: ''
source_type: 4
source_version: ''
start_time: 1636344866307
status: 3
tags: []
user_id: root
