artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/13/8ef7663e6e0c4669a6d16971736b3c94/artifacts
end_time: 1636475672239
entry_point_name: ''
experiment_id: '13'
lifecycle_stage: active
name: ''
run_id: 8ef7663e6e0c4669a6d16971736b3c94
run_uuid: 8ef7663e6e0c4669a6d16971736b3c94
source_name: ''
source_type: 4
source_version: ''
start_time: 1636475672224
status: 3
tags: []
user_id: root
