artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/13/a9073f6bf7e241a9a1f93875b76f2d95/artifacts
end_time: 1636475147119
entry_point_name: ''
experiment_id: '13'
lifecycle_stage: active
name: ''
run_id: a9073f6bf7e241a9a1f93875b76f2d95
run_uuid: a9073f6bf7e241a9a1f93875b76f2d95
source_name: ''
source_type: 4
source_version: ''
start_time: 1636475147105
status: 3
tags: []
user_id: root
