artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/5/cf6fa767fcd0468a9bbd462847e8c804/artifacts
end_time: 1636344614803
entry_point_name: ''
experiment_id: '5'
lifecycle_stage: active
name: ''
run_id: cf6fa767fcd0468a9bbd462847e8c804
run_uuid: cf6fa767fcd0468a9bbd462847e8c804
source_name: ''
source_type: 4
source_version: ''
start_time: 1636344614794
status: 3
tags: []
user_id: root
