artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/6/14daa456750b4347bd1e45a26df0cdfb/artifacts
end_time: 1636407001849
entry_point_name: ''
experiment_id: '6'
lifecycle_stage: active
name: ''
run_id: 14daa456750b4347bd1e45a26df0cdfb
run_uuid: 14daa456750b4347bd1e45a26df0cdfb
source_name: ''
source_type: 4
source_version: ''
start_time: 1636407001838
status: 3
tags: []
user_id: root
