artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/9/a3632fe299164fa18f7a9d3b03f05106/artifacts
end_time: 1636420066389
entry_point_name: ''
experiment_id: '9'
lifecycle_stage: active
name: ''
run_id: a3632fe299164fa18f7a9d3b03f05106
run_uuid: a3632fe299164fa18f7a9d3b03f05106
source_name: ''
source_type: 4
source_version: ''
start_time: 1636420065955
status: 4
tags: []
user_id: root
