artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/6/83f26de9b1cb4ade91ec1eb8fd27fc49/artifacts
end_time: 1636407181046
entry_point_name: ''
experiment_id: '6'
lifecycle_stage: active
name: ''
run_id: 83f26de9b1cb4ade91ec1eb8fd27fc49
run_uuid: 83f26de9b1cb4ade91ec1eb8fd27fc49
source_name: ''
source_type: 4
source_version: ''
start_time: 1636407181035
status: 3
tags: []
user_id: root
