artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/6/f2c663006981427a8a5f345d889ee561/artifacts
end_time: 1636406892403
entry_point_name: ''
experiment_id: '6'
lifecycle_stage: active
name: ''
run_id: f2c663006981427a8a5f345d889ee561
run_uuid: f2c663006981427a8a5f345d889ee561
source_name: ''
source_type: 4
source_version: ''
start_time: 1636406892392
status: 3
tags: []
user_id: root
