artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/2/a198a6751bea4312a93cb5cd2713bd2c/artifacts
end_time: 1636331242806
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: a198a6751bea4312a93cb5cd2713bd2c
run_uuid: a198a6751bea4312a93cb5cd2713bd2c
source_name: ''
source_type: 4
source_version: ''
start_time: 1636331242798
status: 3
tags: []
user_id: root
