artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/5/ff8041be9d3d43179b9f12c6b6e1e04b/artifacts
end_time: 1636343156819
entry_point_name: ''
experiment_id: '5'
lifecycle_stage: active
name: ''
run_id: ff8041be9d3d43179b9f12c6b6e1e04b
run_uuid: ff8041be9d3d43179b9f12c6b6e1e04b
source_name: ''
source_type: 4
source_version: ''
start_time: 1636343156811
status: 3
tags: []
user_id: root
