artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/7/69c2225ddf074222b194a90315f3614a/artifacts
end_time: 1636411007033
entry_point_name: ''
experiment_id: '7'
lifecycle_stage: active
name: ''
run_id: 69c2225ddf074222b194a90315f3614a
run_uuid: 69c2225ddf074222b194a90315f3614a
source_name: ''
source_type: 4
source_version: ''
start_time: 1636411007023
status: 3
tags: []
user_id: root
