artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/12/9c8b7640ee0e4785af5cd1fd17d55d75/artifacts
end_time: 1636470379188
entry_point_name: ''
experiment_id: '12'
lifecycle_stage: active
name: ''
run_id: 9c8b7640ee0e4785af5cd1fd17d55d75
run_uuid: 9c8b7640ee0e4785af5cd1fd17d55d75
source_name: ''
source_type: 4
source_version: ''
start_time: 1636470366812
status: 3
tags: []
user_id: root
