artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/2/021afe2a618a4b6da018c96d178ca732/artifacts
end_time: 1636338525044
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 021afe2a618a4b6da018c96d178ca732
run_uuid: 021afe2a618a4b6da018c96d178ca732
source_name: ''
source_type: 4
source_version: ''
start_time: 1636338525030
status: 3
tags: []
user_id: root
