artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/13/c230b20b43954ae9bcba232ebae1817d/artifacts
end_time: 1636475709225
entry_point_name: ''
experiment_id: '13'
lifecycle_stage: active
name: ''
run_id: c230b20b43954ae9bcba232ebae1817d
run_uuid: c230b20b43954ae9bcba232ebae1817d
source_name: ''
source_type: 4
source_version: ''
start_time: 1636475709211
status: 3
tags: []
user_id: root
