artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/7/4609853855ee4ab88a88ade094a50153/artifacts
end_time: 1636410685199
entry_point_name: ''
experiment_id: '7'
lifecycle_stage: active
name: ''
run_id: 4609853855ee4ab88a88ade094a50153
run_uuid: 4609853855ee4ab88a88ade094a50153
source_name: ''
source_type: 4
source_version: ''
start_time: 1636410685189
status: 3
tags: []
user_id: root
