artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/2/4fdf65587005480f8bb727f3caa9915f/artifacts
end_time: 1636333068394
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 4fdf65587005480f8bb727f3caa9915f
run_uuid: 4fdf65587005480f8bb727f3caa9915f
source_name: ''
source_type: 4
source_version: ''
start_time: 1636333068387
status: 3
tags: []
user_id: root
