artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/5/ad800a3330be4d9da08131375e76d020/artifacts
end_time: 1636345977985
entry_point_name: ''
experiment_id: '5'
lifecycle_stage: active
name: ''
run_id: ad800a3330be4d9da08131375e76d020
run_uuid: ad800a3330be4d9da08131375e76d020
source_name: ''
source_type: 4
source_version: ''
start_time: 1636345977976
status: 3
tags: []
user_id: root
