artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/13/7dff5026a1614b99be9c5b4067861819/artifacts
end_time: 1636476111778
entry_point_name: ''
experiment_id: '13'
lifecycle_stage: active
name: ''
run_id: 7dff5026a1614b99be9c5b4067861819
run_uuid: 7dff5026a1614b99be9c5b4067861819
source_name: ''
source_type: 4
source_version: ''
start_time: 1636476111765
status: 3
tags: []
user_id: root
