artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/2/2964d00f56904a5faa160c46348f0ed6/artifacts
end_time: 1636333177890
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 2964d00f56904a5faa160c46348f0ed6
run_uuid: 2964d00f56904a5faa160c46348f0ed6
source_name: ''
source_type: 4
source_version: ''
start_time: 1636333177883
status: 3
tags: []
user_id: root
