artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/9/5a96daa4b55043aabb50b01c30cf8632/artifacts
end_time: 1636421078671
entry_point_name: ''
experiment_id: '9'
lifecycle_stage: active
name: ''
run_id: 5a96daa4b55043aabb50b01c30cf8632
run_uuid: 5a96daa4b55043aabb50b01c30cf8632
source_name: ''
source_type: 4
source_version: ''
start_time: 1636421061603
status: 3
tags: []
user_id: root
