artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/7/6f0b7be6d0ae46539a321f9f8195cbf4/artifacts
end_time: 1636411992306
entry_point_name: ''
experiment_id: '7'
lifecycle_stage: active
name: ''
run_id: 6f0b7be6d0ae46539a321f9f8195cbf4
run_uuid: 6f0b7be6d0ae46539a321f9f8195cbf4
source_name: ''
source_type: 4
source_version: ''
start_time: 1636411992296
status: 3
tags: []
user_id: root
