artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/7/494b0ddac39b4ddcb4801b02a2c00226/artifacts
end_time: 1636413885667
entry_point_name: ''
experiment_id: '7'
lifecycle_stage: active
name: ''
run_id: 494b0ddac39b4ddcb4801b02a2c00226
run_uuid: 494b0ddac39b4ddcb4801b02a2c00226
source_name: ''
source_type: 4
source_version: ''
start_time: 1636413885657
status: 3
tags: []
user_id: root
