artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/3/83d5bb8cc09b45d599e50f5f69172f16/artifacts
end_time: 1636341569872
entry_point_name: ''
experiment_id: '3'
lifecycle_stage: active
name: ''
run_id: 83d5bb8cc09b45d599e50f5f69172f16
run_uuid: 83d5bb8cc09b45d599e50f5f69172f16
source_name: ''
source_type: 4
source_version: ''
start_time: 1636341569863
status: 3
tags: []
user_id: root
