artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/5/c0fa7b936c64484284bb300909241dd2/artifacts
end_time: 1636345476125
entry_point_name: ''
experiment_id: '5'
lifecycle_stage: active
name: ''
run_id: c0fa7b936c64484284bb300909241dd2
run_uuid: c0fa7b936c64484284bb300909241dd2
source_name: ''
source_type: 4
source_version: ''
start_time: 1636345476116
status: 3
tags: []
user_id: root
