artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/6/326a0af372d549858eeae07afbb7405b/artifacts
end_time: 1636405652022
entry_point_name: ''
experiment_id: '6'
lifecycle_stage: active
name: ''
run_id: 326a0af372d549858eeae07afbb7405b
run_uuid: 326a0af372d549858eeae07afbb7405b
source_name: ''
source_type: 4
source_version: ''
start_time: 1636405652012
status: 3
tags: []
user_id: root
