artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/2/5f7e80466a8f4336a2f2ee5f39ef1dfd/artifacts
end_time: 1636337098203
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 5f7e80466a8f4336a2f2ee5f39ef1dfd
run_uuid: 5f7e80466a8f4336a2f2ee5f39ef1dfd
source_name: ''
source_type: 4
source_version: ''
start_time: 1636337098195
status: 3
tags: []
user_id: root
