artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/7/4a40548eabe94584b5790e46b8324cc7/artifacts
end_time: 1636411085249
entry_point_name: ''
experiment_id: '7'
lifecycle_stage: active
name: ''
run_id: 4a40548eabe94584b5790e46b8324cc7
run_uuid: 4a40548eabe94584b5790e46b8324cc7
source_name: ''
source_type: 4
source_version: ''
start_time: 1636411085240
status: 3
tags: []
user_id: root
