artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/7/7aa31c6c4a84409583c17e88e06578d1/artifacts
end_time: 1636410819748
entry_point_name: ''
experiment_id: '7'
lifecycle_stage: active
name: ''
run_id: 7aa31c6c4a84409583c17e88e06578d1
run_uuid: 7aa31c6c4a84409583c17e88e06578d1
source_name: ''
source_type: 4
source_version: ''
start_time: 1636410819738
status: 3
tags: []
user_id: root
