artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/2/c8f1f9b215f348b18e05f70383790f9c/artifacts
end_time: 1636335009238
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: c8f1f9b215f348b18e05f70383790f9c
run_uuid: c8f1f9b215f348b18e05f70383790f9c
source_name: ''
source_type: 4
source_version: ''
start_time: 1636335009230
status: 3
tags: []
user_id: root
