artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/7/b8ba828dacac4070af63f8a3b42236d1/artifacts
end_time: 1636410513188
entry_point_name: ''
experiment_id: '7'
lifecycle_stage: active
name: ''
run_id: b8ba828dacac4070af63f8a3b42236d1
run_uuid: b8ba828dacac4070af63f8a3b42236d1
source_name: ''
source_type: 4
source_version: ''
start_time: 1636410513177
status: 3
tags: []
user_id: root
