artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/6/e2a168c7c6e14e4ea4aff0c0d7bb0520/artifacts
end_time: 1636405550360
entry_point_name: ''
experiment_id: '6'
lifecycle_stage: active
name: ''
run_id: e2a168c7c6e14e4ea4aff0c0d7bb0520
run_uuid: e2a168c7c6e14e4ea4aff0c0d7bb0520
source_name: ''
source_type: 4
source_version: ''
start_time: 1636405550349
status: 3
tags: []
user_id: root
