artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/11/473f26e3d6f9492cb423aa8ca98b285c/artifacts
end_time: 1636439449964
entry_point_name: ''
experiment_id: '11'
lifecycle_stage: active
name: ''
run_id: 473f26e3d6f9492cb423aa8ca98b285c
run_uuid: 473f26e3d6f9492cb423aa8ca98b285c
source_name: ''
source_type: 4
source_version: ''
start_time: 1636439449954
status: 3
tags: []
user_id: root
