artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/7/bc9b555ec01441d98ae6887520157c7e/artifacts
end_time: 1636415281944
entry_point_name: ''
experiment_id: '7'
lifecycle_stage: active
name: ''
run_id: bc9b555ec01441d98ae6887520157c7e
run_uuid: bc9b555ec01441d98ae6887520157c7e
source_name: ''
source_type: 4
source_version: ''
start_time: 1636415281934
status: 3
tags: []
user_id: root
