artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/11/7ac71e0fbe494b6e82a4c4894a7b9ee4/artifacts
end_time: 1636437048602
entry_point_name: ''
experiment_id: '11'
lifecycle_stage: active
name: ''
run_id: 7ac71e0fbe494b6e82a4c4894a7b9ee4
run_uuid: 7ac71e0fbe494b6e82a4c4894a7b9ee4
source_name: ''
source_type: 4
source_version: ''
start_time: 1636437048592
status: 3
tags: []
user_id: root
