artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/2/9e14aafa66d14dbba07445582bae3333/artifacts
end_time: 1636337937106
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 9e14aafa66d14dbba07445582bae3333
run_uuid: 9e14aafa66d14dbba07445582bae3333
source_name: ''
source_type: 4
source_version: ''
start_time: 1636337937098
status: 3
tags: []
user_id: root
