artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/2/07e67aefe3364805a82aa4dae6be2902/artifacts
end_time: 1636340314773
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 07e67aefe3364805a82aa4dae6be2902
run_uuid: 07e67aefe3364805a82aa4dae6be2902
source_name: ''
source_type: 4
source_version: ''
start_time: 1636340074230
status: 3
tags: []
user_id: root
