artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/5/0f04abe86aae4c779726adc845b253fb/artifacts
end_time: 1636344932343
entry_point_name: ''
experiment_id: '5'
lifecycle_stage: active
name: ''
run_id: 0f04abe86aae4c779726adc845b253fb
run_uuid: 0f04abe86aae4c779726adc845b253fb
source_name: ''
source_type: 4
source_version: ''
start_time: 1636344932335
status: 3
tags: []
user_id: root
