artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/7/91f87c74d6b84d8bb9559d62a9f22bee/artifacts
end_time: 1636411776840
entry_point_name: ''
experiment_id: '7'
lifecycle_stage: active
name: ''
run_id: 91f87c74d6b84d8bb9559d62a9f22bee
run_uuid: 91f87c74d6b84d8bb9559d62a9f22bee
source_name: ''
source_type: 4
source_version: ''
start_time: 1636411776830
status: 3
tags: []
user_id: root
