artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/5/abe15a755e1b46dbb4dc12777e2c4689/artifacts
end_time: 1636346095417
entry_point_name: ''
experiment_id: '5'
lifecycle_stage: active
name: ''
run_id: abe15a755e1b46dbb4dc12777e2c4689
run_uuid: abe15a755e1b46dbb4dc12777e2c4689
source_name: ''
source_type: 4
source_version: ''
start_time: 1636346095409
status: 3
tags: []
user_id: root
