artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/9/dec72cef4dfe44cd888859495667d983/artifacts
end_time: 1636420817361
entry_point_name: ''
experiment_id: '9'
lifecycle_stage: active
name: ''
run_id: dec72cef4dfe44cd888859495667d983
run_uuid: dec72cef4dfe44cd888859495667d983
source_name: ''
source_type: 4
source_version: ''
start_time: 1636420800519
status: 3
tags: []
user_id: root
