artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/6/a06c31ac05794cc1a08b7674cba82ba2/artifacts
end_time: 1636408102633
entry_point_name: ''
experiment_id: '6'
lifecycle_stage: active
name: ''
run_id: a06c31ac05794cc1a08b7674cba82ba2
run_uuid: a06c31ac05794cc1a08b7674cba82ba2
source_name: ''
source_type: 4
source_version: ''
start_time: 1636408102622
status: 3
tags: []
user_id: root
