artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/6/6234bbe8441742f095d8cdc071d2b880/artifacts
end_time: 1636408429103
entry_point_name: ''
experiment_id: '6'
lifecycle_stage: active
name: ''
run_id: 6234bbe8441742f095d8cdc071d2b880
run_uuid: 6234bbe8441742f095d8cdc071d2b880
source_name: ''
source_type: 4
source_version: ''
start_time: 1636408429092
status: 3
tags: []
user_id: root
