artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/7/f71c2421d8564d42af71e799cb318300/artifacts
end_time: 1636412327895
entry_point_name: ''
experiment_id: '7'
lifecycle_stage: active
name: ''
run_id: f71c2421d8564d42af71e799cb318300
run_uuid: f71c2421d8564d42af71e799cb318300
source_name: ''
source_type: 4
source_version: ''
start_time: 1636412327885
status: 3
tags: []
user_id: root
