artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/2/11dd2475486743c5b9e02e78e187f942/artifacts
end_time: 1636332359957
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 11dd2475486743c5b9e02e78e187f942
run_uuid: 11dd2475486743c5b9e02e78e187f942
source_name: ''
source_type: 4
source_version: ''
start_time: 1636332359950
status: 3
tags: []
user_id: root
