artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/6/252c801f87b0474ab064e2c82c2c72fc/artifacts
end_time: 1636406421765
entry_point_name: ''
experiment_id: '6'
lifecycle_stage: active
name: ''
run_id: 252c801f87b0474ab064e2c82c2c72fc
run_uuid: 252c801f87b0474ab064e2c82c2c72fc
source_name: ''
source_type: 4
source_version: ''
start_time: 1636406421755
status: 3
tags: []
user_id: root
