artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/6/cc21fb0055384fd2a891193dbd7e2303/artifacts
end_time: 1636406698180
entry_point_name: ''
experiment_id: '6'
lifecycle_stage: active
name: ''
run_id: cc21fb0055384fd2a891193dbd7e2303
run_uuid: cc21fb0055384fd2a891193dbd7e2303
source_name: ''
source_type: 4
source_version: ''
start_time: 1636406698160
status: 3
tags: []
user_id: root
