artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/7/217426f4be53403b8f13b19363ab9142/artifacts
end_time: 1636411868980
entry_point_name: ''
experiment_id: '7'
lifecycle_stage: active
name: ''
run_id: 217426f4be53403b8f13b19363ab9142
run_uuid: 217426f4be53403b8f13b19363ab9142
source_name: ''
source_type: 4
source_version: ''
start_time: 1636411868970
status: 3
tags: []
user_id: root
