artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/5/4f1d57d940154de7afd9ebdf055d8052/artifacts
end_time: 1636343255945
entry_point_name: ''
experiment_id: '5'
lifecycle_stage: active
name: ''
run_id: 4f1d57d940154de7afd9ebdf055d8052
run_uuid: 4f1d57d940154de7afd9ebdf055d8052
source_name: ''
source_type: 4
source_version: ''
start_time: 1636343255936
status: 3
tags: []
user_id: root
