artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/7/ee75145378f8431a90f5e4ce4edea172/artifacts
end_time: 1636413306179
entry_point_name: ''
experiment_id: '7'
lifecycle_stage: active
name: ''
run_id: ee75145378f8431a90f5e4ce4edea172
run_uuid: ee75145378f8431a90f5e4ce4edea172
source_name: ''
source_type: 4
source_version: ''
start_time: 1636413306169
status: 3
tags: []
user_id: root
