artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/6/4de4518f70384f4580095ad8a2310c54/artifacts
end_time: 1636406522640
entry_point_name: ''
experiment_id: '6'
lifecycle_stage: active
name: ''
run_id: 4de4518f70384f4580095ad8a2310c54
run_uuid: 4de4518f70384f4580095ad8a2310c54
source_name: ''
source_type: 4
source_version: ''
start_time: 1636406522629
status: 3
tags: []
user_id: root
