artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/7/8774ad00d58042cd95c882ae84c51f03/artifacts
end_time: 1636413152289
entry_point_name: ''
experiment_id: '7'
lifecycle_stage: active
name: ''
run_id: 8774ad00d58042cd95c882ae84c51f03
run_uuid: 8774ad00d58042cd95c882ae84c51f03
source_name: ''
source_type: 4
source_version: ''
start_time: 1636413152278
status: 3
tags: []
user_id: root
