artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/6/57ede4803dea4e0fbc8ff6906f64615e/artifacts
end_time: 1636407079572
entry_point_name: ''
experiment_id: '6'
lifecycle_stage: active
name: ''
run_id: 57ede4803dea4e0fbc8ff6906f64615e
run_uuid: 57ede4803dea4e0fbc8ff6906f64615e
source_name: ''
source_type: 4
source_version: ''
start_time: 1636407079562
status: 3
tags: []
user_id: root
