artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/5/1ebe133bba9e424bbf7f2fd3bdd30021/artifacts
end_time: 1636345010054
entry_point_name: ''
experiment_id: '5'
lifecycle_stage: active
name: ''
run_id: 1ebe133bba9e424bbf7f2fd3bdd30021
run_uuid: 1ebe133bba9e424bbf7f2fd3bdd30021
source_name: ''
source_type: 4
source_version: ''
start_time: 1636345010045
status: 3
tags: []
user_id: root
