artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/7/2a5ca37654c94679bad2809cd0009323/artifacts
end_time: 1636414505428
entry_point_name: ''
experiment_id: '7'
lifecycle_stage: active
name: ''
run_id: 2a5ca37654c94679bad2809cd0009323
run_uuid: 2a5ca37654c94679bad2809cd0009323
source_name: ''
source_type: 4
source_version: ''
start_time: 1636414505418
status: 3
tags: []
user_id: root
