artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/1/e05c05d1eadd423d824f32d22aefa705/artifacts
end_time: 1636319497940
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: e05c05d1eadd423d824f32d22aefa705
run_uuid: e05c05d1eadd423d824f32d22aefa705
source_name: ''
source_type: 4
source_version: ''
start_time: 1636319497932
status: 3
tags: []
user_id: root
