artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/9/88f69222c1b748dc926757f0d18e5d63/artifacts
end_time: 1636420569436
entry_point_name: ''
experiment_id: '9'
lifecycle_stage: active
name: ''
run_id: 88f69222c1b748dc926757f0d18e5d63
run_uuid: 88f69222c1b748dc926757f0d18e5d63
source_name: ''
source_type: 4
source_version: ''
start_time: 1636420559305
status: 3
tags: []
user_id: root
