artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/5/c3664bae919348ab9204f70ec0c68893/artifacts
end_time: 1636347036456
entry_point_name: ''
experiment_id: '5'
lifecycle_stage: active
name: ''
run_id: c3664bae919348ab9204f70ec0c68893
run_uuid: c3664bae919348ab9204f70ec0c68893
source_name: ''
source_type: 4
source_version: ''
start_time: 1636347036447
status: 3
tags: []
user_id: root
