artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/13/e74ddf3aa17f4bca9a2bd2c4c313e3f4/artifacts
end_time: 1636475231327
entry_point_name: ''
experiment_id: '13'
lifecycle_stage: active
name: ''
run_id: e74ddf3aa17f4bca9a2bd2c4c313e3f4
run_uuid: e74ddf3aa17f4bca9a2bd2c4c313e3f4
source_name: ''
source_type: 4
source_version: ''
start_time: 1636475231314
status: 3
tags: []
user_id: root
