artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/2/e6e536b50fd349f88f660b9783041ed9/artifacts
end_time: 1636330862072
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: e6e536b50fd349f88f660b9783041ed9
run_uuid: e6e536b50fd349f88f660b9783041ed9
source_name: ''
source_type: 4
source_version: ''
start_time: 1636330862064
status: 3
tags: []
user_id: root
