artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/13/166aa0c31f864c90843c41ccec49883d/artifacts
end_time: 1636475589750
entry_point_name: ''
experiment_id: '13'
lifecycle_stage: active
name: ''
run_id: 166aa0c31f864c90843c41ccec49883d
run_uuid: 166aa0c31f864c90843c41ccec49883d
source_name: ''
source_type: 4
source_version: ''
start_time: 1636475589737
status: 3
tags: []
user_id: root
