artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/1/d689d23c65614e04aa920ae83f6970fe/artifacts
end_time: 1636320939709
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: d689d23c65614e04aa920ae83f6970fe
run_uuid: d689d23c65614e04aa920ae83f6970fe
source_name: ''
source_type: 4
source_version: ''
start_time: 1636320939702
status: 3
tags: []
user_id: root
