artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/13/fd204caab2e5486da458dc3e45aef1d8/artifacts
end_time: 1636474741210
entry_point_name: ''
experiment_id: '13'
lifecycle_stage: active
name: ''
run_id: fd204caab2e5486da458dc3e45aef1d8
run_uuid: fd204caab2e5486da458dc3e45aef1d8
source_name: ''
source_type: 4
source_version: ''
start_time: 1636474741197
status: 3
tags: []
user_id: root
