artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/6/ddad65a8450449b381f154ff8a7f5929/artifacts
end_time: 1636407270582
entry_point_name: ''
experiment_id: '6'
lifecycle_stage: active
name: ''
run_id: ddad65a8450449b381f154ff8a7f5929
run_uuid: ddad65a8450449b381f154ff8a7f5929
source_name: ''
source_type: 4
source_version: ''
start_time: 1636407270570
status: 3
tags: []
user_id: root
