artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/2/ae9c127c199540e2ac63ea7903b383b0/artifacts
end_time: 1636331675041
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: ae9c127c199540e2ac63ea7903b383b0
run_uuid: ae9c127c199540e2ac63ea7903b383b0
source_name: ''
source_type: 4
source_version: ''
start_time: 1636331675032
status: 3
tags: []
user_id: root
