artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/5/67e3c757a5bf45559b044b36b6e34d20/artifacts
end_time: 1636345720882
entry_point_name: ''
experiment_id: '5'
lifecycle_stage: active
name: ''
run_id: 67e3c757a5bf45559b044b36b6e34d20
run_uuid: 67e3c757a5bf45559b044b36b6e34d20
source_name: ''
source_type: 4
source_version: ''
start_time: 1636345720873
status: 3
tags: []
user_id: root
