artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/9/822a82b8c2a54a29a1f4c526bee38ad0/artifacts
end_time: 1636421287509
entry_point_name: ''
experiment_id: '9'
lifecycle_stage: active
name: ''
run_id: 822a82b8c2a54a29a1f4c526bee38ad0
run_uuid: 822a82b8c2a54a29a1f4c526bee38ad0
source_name: ''
source_type: 4
source_version: ''
start_time: 1636421273707
status: 3
tags: []
user_id: root
