artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/6/bed9d930de6e413f859a5d4fbd3dcffe/artifacts
end_time: 1636404068174
entry_point_name: ''
experiment_id: '6'
lifecycle_stage: active
name: ''
run_id: bed9d930de6e413f859a5d4fbd3dcffe
run_uuid: bed9d930de6e413f859a5d4fbd3dcffe
source_name: ''
source_type: 4
source_version: ''
start_time: 1636404068163
status: 3
tags: []
user_id: root
