artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/7/f91e4f81b26c41fc8a5d0caccac41461/artifacts
end_time: 1636411425766
entry_point_name: ''
experiment_id: '7'
lifecycle_stage: active
name: ''
run_id: f91e4f81b26c41fc8a5d0caccac41461
run_uuid: f91e4f81b26c41fc8a5d0caccac41461
source_name: ''
source_type: 4
source_version: ''
start_time: 1636411425756
status: 3
tags: []
user_id: root
