artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/6/c0f7b214f6344bffa619571da8bc1d72/artifacts
end_time: 1636404648678
entry_point_name: ''
experiment_id: '6'
lifecycle_stage: active
name: ''
run_id: c0f7b214f6344bffa619571da8bc1d72
run_uuid: c0f7b214f6344bffa619571da8bc1d72
source_name: ''
source_type: 4
source_version: ''
start_time: 1636404648668
status: 3
tags: []
user_id: root
