artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/7/1f0fd9d1488349a6b2a874c6d25fb547/artifacts
end_time: 1636415798162
entry_point_name: ''
experiment_id: '7'
lifecycle_stage: active
name: ''
run_id: 1f0fd9d1488349a6b2a874c6d25fb547
run_uuid: 1f0fd9d1488349a6b2a874c6d25fb547
source_name: ''
source_type: 4
source_version: ''
start_time: 1636415798151
status: 3
tags: []
user_id: root
