artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/2/f1196c9ce4c04b588777cfbf60cab73f/artifacts
end_time: 1636338124555
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: f1196c9ce4c04b588777cfbf60cab73f
run_uuid: f1196c9ce4c04b588777cfbf60cab73f
source_name: ''
source_type: 4
source_version: ''
start_time: 1636338124547
status: 3
tags: []
user_id: root
