artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/7/c30775adcba04e339d319f4d45ecd5d8/artifacts
end_time: 1636413820877
entry_point_name: ''
experiment_id: '7'
lifecycle_stage: active
name: ''
run_id: c30775adcba04e339d319f4d45ecd5d8
run_uuid: c30775adcba04e339d319f4d45ecd5d8
source_name: ''
source_type: 4
source_version: ''
start_time: 1636413820867
status: 3
tags: []
user_id: root
