artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/13/f7ea8abecf864103ab534cbae7363e08/artifacts
end_time: 1636476270489
entry_point_name: ''
experiment_id: '13'
lifecycle_stage: active
name: ''
run_id: f7ea8abecf864103ab534cbae7363e08
run_uuid: f7ea8abecf864103ab534cbae7363e08
source_name: ''
source_type: 4
source_version: ''
start_time: 1636476270475
status: 3
tags: []
user_id: root
