artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/8/8efaff305a8f4b339483ba0f27fc624f/artifacts
end_time: 1636418402749
entry_point_name: ''
experiment_id: '8'
lifecycle_stage: active
name: ''
run_id: 8efaff305a8f4b339483ba0f27fc624f
run_uuid: 8efaff305a8f4b339483ba0f27fc624f
source_name: ''
source_type: 4
source_version: ''
start_time: 1636418394012
status: 3
tags: []
user_id: root
