artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/11/6ebd7d6aa50f486e8318cbd3314bd338/artifacts
end_time: 1636438242719
entry_point_name: ''
experiment_id: '11'
lifecycle_stage: active
name: ''
run_id: 6ebd7d6aa50f486e8318cbd3314bd338
run_uuid: 6ebd7d6aa50f486e8318cbd3314bd338
source_name: ''
source_type: 4
source_version: ''
start_time: 1636438242709
status: 3
tags: []
user_id: root
