artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/6/05e8e47f4d104bbda7803f66cdb0f507/artifacts
end_time: 1636405770034
entry_point_name: ''
experiment_id: '6'
lifecycle_stage: active
name: ''
run_id: 05e8e47f4d104bbda7803f66cdb0f507
run_uuid: 05e8e47f4d104bbda7803f66cdb0f507
source_name: ''
source_type: 4
source_version: ''
start_time: 1636405770024
status: 3
tags: []
user_id: root
