artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/6/d1fb6eaed11e4a22b0f5e67fd5046025/artifacts
end_time: 1636404293141
entry_point_name: ''
experiment_id: '6'
lifecycle_stage: active
name: ''
run_id: d1fb6eaed11e4a22b0f5e67fd5046025
run_uuid: d1fb6eaed11e4a22b0f5e67fd5046025
source_name: ''
source_type: 4
source_version: ''
start_time: 1636404293131
status: 3
tags: []
user_id: root
