artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/6/5d1d9aed8b2f411ea6a9a9537d0fdb3e/artifacts
end_time: 1636407362629
entry_point_name: ''
experiment_id: '6'
lifecycle_stage: active
name: ''
run_id: 5d1d9aed8b2f411ea6a9a9537d0fdb3e
run_uuid: 5d1d9aed8b2f411ea6a9a9537d0fdb3e
source_name: ''
source_type: 4
source_version: ''
start_time: 1636407362619
status: 3
tags: []
user_id: root
