artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/9/abf0489d99de478baea5f4c73ec547cc/artifacts
end_time: 1636421371789
entry_point_name: ''
experiment_id: '9'
lifecycle_stage: active
name: ''
run_id: abf0489d99de478baea5f4c73ec547cc
run_uuid: abf0489d99de478baea5f4c73ec547cc
source_name: ''
source_type: 4
source_version: ''
start_time: 1636421349262
status: 3
tags: []
user_id: root
