artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/13/d490a227a96543fba3906f18b1aafac4/artifacts
end_time: 1636474165003
entry_point_name: ''
experiment_id: '13'
lifecycle_stage: active
name: ''
run_id: d490a227a96543fba3906f18b1aafac4
run_uuid: d490a227a96543fba3906f18b1aafac4
source_name: ''
source_type: 4
source_version: ''
start_time: 1636474164990
status: 3
tags: []
user_id: root
