artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/6/6544e1d7d409419bb8c84ecc3955c909/artifacts
end_time: 1636408316097
entry_point_name: ''
experiment_id: '6'
lifecycle_stage: active
name: ''
run_id: 6544e1d7d409419bb8c84ecc3955c909
run_uuid: 6544e1d7d409419bb8c84ecc3955c909
source_name: ''
source_type: 4
source_version: ''
start_time: 1636408316086
status: 3
tags: []
user_id: root
