artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/5/4790e1b62bed45d1ab582c4d02d9408f/artifacts
end_time: 1636347118302
entry_point_name: ''
experiment_id: '5'
lifecycle_stage: active
name: ''
run_id: 4790e1b62bed45d1ab582c4d02d9408f
run_uuid: 4790e1b62bed45d1ab582c4d02d9408f
source_name: ''
source_type: 4
source_version: ''
start_time: 1636347118294
status: 3
tags: []
user_id: root
