artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/2/12a8568a9c0148539ceb59ee37d37395/artifacts
end_time: 1636338928471
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 12a8568a9c0148539ceb59ee37d37395
run_uuid: 12a8568a9c0148539ceb59ee37d37395
source_name: ''
source_type: 4
source_version: ''
start_time: 1636338928463
status: 3
tags: []
user_id: root
