artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/13/0d44a785813d44459f5bb93ed20dd587/artifacts
end_time: 1636474955023
entry_point_name: ''
experiment_id: '13'
lifecycle_stage: active
name: ''
run_id: 0d44a785813d44459f5bb93ed20dd587
run_uuid: 0d44a785813d44459f5bb93ed20dd587
source_name: ''
source_type: 4
source_version: ''
start_time: 1636474955010
status: 3
tags: []
user_id: root
