artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/7/eacbb09b378642d8ad71ceda0c6b7b55/artifacts
end_time: 1636415201210
entry_point_name: ''
experiment_id: '7'
lifecycle_stage: active
name: ''
run_id: eacbb09b378642d8ad71ceda0c6b7b55
run_uuid: eacbb09b378642d8ad71ceda0c6b7b55
source_name: ''
source_type: 4
source_version: ''
start_time: 1636415201199
status: 3
tags: []
user_id: root
