artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/9/3ef3c882c4d84fbe95ea60fbc326da06/artifacts
end_time: 1636420634287
entry_point_name: ''
experiment_id: '9'
lifecycle_stage: active
name: ''
run_id: 3ef3c882c4d84fbe95ea60fbc326da06
run_uuid: 3ef3c882c4d84fbe95ea60fbc326da06
source_name: ''
source_type: 4
source_version: ''
start_time: 1636420617857
status: 3
tags: []
user_id: root
