artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/5/e53c5134d5ed4f5197d99476090d8b88/artifacts
end_time: 1636346887979
entry_point_name: ''
experiment_id: '5'
lifecycle_stage: active
name: ''
run_id: e53c5134d5ed4f5197d99476090d8b88
run_uuid: e53c5134d5ed4f5197d99476090d8b88
source_name: ''
source_type: 4
source_version: ''
start_time: 1636346887971
status: 3
tags: []
user_id: root
