artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/13/51c6cfb6323147618f9304c2b3abd641/artifacts
end_time: 1636475181402
entry_point_name: ''
experiment_id: '13'
lifecycle_stage: active
name: ''
run_id: 51c6cfb6323147618f9304c2b3abd641
run_uuid: 51c6cfb6323147618f9304c2b3abd641
source_name: ''
source_type: 4
source_version: ''
start_time: 1636475181388
status: 3
tags: []
user_id: root
