artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/9/b3095d84da3a4b9b9e354224fea2d535/artifacts
end_time: 1636432890693
entry_point_name: ''
experiment_id: '9'
lifecycle_stage: active
name: ''
run_id: b3095d84da3a4b9b9e354224fea2d535
run_uuid: b3095d84da3a4b9b9e354224fea2d535
source_name: ''
source_type: 4
source_version: ''
start_time: 1636432868668
status: 3
tags: []
user_id: root
