artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/14/dd5d0a432365458db3dd49af653e22d0/artifacts
end_time: 1638143604805
entry_point_name: ''
experiment_id: '14'
lifecycle_stage: active
name: ''
run_id: dd5d0a432365458db3dd49af653e22d0
run_uuid: dd5d0a432365458db3dd49af653e22d0
source_name: ''
source_type: 4
source_version: ''
start_time: 1638143604102
status: 4
tags: []
user_id: kaushik
