artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/7/f2099ed7fe214e51b2608ffa5c25b36e/artifacts
end_time: 1636411215270
entry_point_name: ''
experiment_id: '7'
lifecycle_stage: active
name: ''
run_id: f2099ed7fe214e51b2608ffa5c25b36e
run_uuid: f2099ed7fe214e51b2608ffa5c25b36e
source_name: ''
source_type: 4
source_version: ''
start_time: 1636411215260
status: 3
tags: []
user_id: root
