artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/6/68844a278e854d0a83299cc2fbc6c4bb/artifacts
end_time: 1636405973582
entry_point_name: ''
experiment_id: '6'
lifecycle_stage: active
name: ''
run_id: 68844a278e854d0a83299cc2fbc6c4bb
run_uuid: 68844a278e854d0a83299cc2fbc6c4bb
source_name: ''
source_type: 4
source_version: ''
start_time: 1636405973572
status: 3
tags: []
user_id: root
