artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/9/b867b764e8514c41bcc0da304b058056/artifacts
end_time: 1636421194881
entry_point_name: ''
experiment_id: '9'
lifecycle_stage: active
name: ''
run_id: b867b764e8514c41bcc0da304b058056
run_uuid: b867b764e8514c41bcc0da304b058056
source_name: ''
source_type: 4
source_version: ''
start_time: 1636421182256
status: 3
tags: []
user_id: root
