artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/13/63065468e18c4a72801c3a53074daaae/artifacts
end_time: 1636475753796
entry_point_name: ''
experiment_id: '13'
lifecycle_stage: active
name: ''
run_id: 63065468e18c4a72801c3a53074daaae
run_uuid: 63065468e18c4a72801c3a53074daaae
source_name: ''
source_type: 4
source_version: ''
start_time: 1636475753783
status: 3
tags: []
user_id: root
