artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/7/bb638660640a46e7af6afd780a5e08ac/artifacts
end_time: 1636414746831
entry_point_name: ''
experiment_id: '7'
lifecycle_stage: active
name: ''
run_id: bb638660640a46e7af6afd780a5e08ac
run_uuid: bb638660640a46e7af6afd780a5e08ac
source_name: ''
source_type: 4
source_version: ''
start_time: 1636414746821
status: 3
tags: []
user_id: root
