artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/6/9f87da33412443f9ac8f2ae11e10a55b/artifacts
end_time: 1636409333195
entry_point_name: ''
experiment_id: '6'
lifecycle_stage: active
name: ''
run_id: 9f87da33412443f9ac8f2ae11e10a55b
run_uuid: 9f87da33412443f9ac8f2ae11e10a55b
source_name: ''
source_type: 4
source_version: ''
start_time: 1636409333185
status: 3
tags: []
user_id: root
