artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/2/6c56ddb0898f4e34923f1c408860c022/artifacts
end_time: 1636337707825
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 6c56ddb0898f4e34923f1c408860c022
run_uuid: 6c56ddb0898f4e34923f1c408860c022
source_name: ''
source_type: 4
source_version: ''
start_time: 1636337707817
status: 3
tags: []
user_id: root
