artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/0/874080b33b054bdf9283a971a32498eb/artifacts
end_time: 1636313375561
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 874080b33b054bdf9283a971a32498eb
run_uuid: 874080b33b054bdf9283a971a32498eb
source_name: ''
source_type: 4
source_version: ''
start_time: 1636313375554
status: 3
tags: []
user_id: root
