artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/13/28978f0235fa4509b574b421dfbbeaff/artifacts
end_time: 1636473764989
entry_point_name: ''
experiment_id: '13'
lifecycle_stage: active
name: ''
run_id: 28978f0235fa4509b574b421dfbbeaff
run_uuid: 28978f0235fa4509b574b421dfbbeaff
source_name: ''
source_type: 4
source_version: ''
start_time: 1636473764975
status: 3
tags: []
user_id: root
