artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/13/7e91122672b140558ed7151e3ffdfb7c/artifacts
end_time: 1636474413061
entry_point_name: ''
experiment_id: '13'
lifecycle_stage: active
name: ''
run_id: 7e91122672b140558ed7151e3ffdfb7c
run_uuid: 7e91122672b140558ed7151e3ffdfb7c
source_name: ''
source_type: 4
source_version: ''
start_time: 1636474413048
status: 3
tags: []
user_id: root
