artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/5/4e8405f3d77e4091af4308e5aa6b6de7/artifacts
end_time: 1636346965783
entry_point_name: ''
experiment_id: '5'
lifecycle_stage: active
name: ''
run_id: 4e8405f3d77e4091af4308e5aa6b6de7
run_uuid: 4e8405f3d77e4091af4308e5aa6b6de7
source_name: ''
source_type: 4
source_version: ''
start_time: 1636346965775
status: 3
tags: []
user_id: root
