artifact_uri: file:///Users/kaushik/MyStuff/Workspace/NEU/DS5500/Project/DS5500_CapstoneProject/mlflow_registry/7/f319786d68dd4362bad8f5500d8bc7fe/artifacts
end_time: 1636413587590
entry_point_name: ''
experiment_id: '7'
lifecycle_stage: active
name: ''
run_id: f319786d68dd4362bad8f5500d8bc7fe
run_uuid: f319786d68dd4362bad8f5500d8bc7fe
source_name: ''
source_type: 4
source_version: ''
start_time: 1636413587579
status: 3
tags: []
user_id: root
